crashinfo: conditional execution according to elevation
crashinfo: print an error message instead of running CrashInfo.jar, if
the user does not have elevated rights, and tries to run the application
with shell privileges. Error code 1 is returned to the parent.

Change-Id: If91067d5cc464d6debcaa0e5ff96c472982b5e5a
Tracked-On: IMINAN-7696
Signed-off-by: Nicolae Natea <nicolaex.natea@intel.com>
Reviewed-on: 232198

diff --git a/crashinfo/crashinfo b/crashinfo/crashinfo
--- a/crashinfo/crashinfo
+++ b/crashinfo/crashinfo
@@ -3,5 +3,14 @@
 base=/system
 export CLASSPATH=$base/framework/crashinfo.jar:$base/framework/crashparsing.jar::$base/framework/com.google.gson.jar
 trap "" HUP
+
+ID=$(id)
+
+if [[ $ID != *root* ]] && [[ $ID != *system* ]] ; then
+    echo "Elevated rights are required to run crashinfo."
+    echo "Please substitute user to root or system"
+    exit 1
+fi
+
 exec app_process $base/bin com.intel.commands.crashinfo.CrashInfo $*
 
